# Generated by Django 3.1.6 on 2021-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('capital', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
