# Generated by Django 2.2.5 on 2020-12-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapp',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
