# Generated by Django 2.2.5 on 2020-12-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0002_formsapp_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsapp',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
