# Generated by Django 2.2.5 on 2020-12-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0003_auto_20201217_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsapp',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
