# Generated by Django 2.2.5 on 2020-12-17 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0005_auto_20201217_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapp',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formsapp',
            name='DateOfEntry',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsapp',
            name='phone_number',
            field=models.IntegerField(default=5),
        ),
    ]
