# Generated by Django 2.2.5 on 2020-12-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0006_auto_20201217_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapp',
            name='DateTimeOfEntry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
