# Generated by Django 2.2.5 on 2020-12-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0008_formsapp_gender_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapp',
            name='imgesAdd',
            field=models.ImageField(default='files', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formsapp',
            name='gender_radio',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
