# Generated by Django 2.2.5 on 2020-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0011_auto_20201217_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapp',
            name='filesUpload',
            field=models.FileField(default='00000', upload_to='templates/files'),
            preserve_default=False,
        ),
    ]
