# Generated by Django 3.1.6 on 2021-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0012_formsapp_filesupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsapp',
            name='filesUpload',
            field=models.FileField(blank=True, upload_to='templates/files'),
        ),
        migrations.AlterField(
            model_name='formsapp',
            name='imgesAdd',
            field=models.ImageField(blank=True, upload_to='templates/images'),
        ),
    ]
