# Generated by Django 3.1.6 on 2021-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0013_auto_20210218_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsapp',
            name='imgesAdd',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
