# Generated by Django 3.1.6 on 2021-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0014_auto_20210218_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsapp',
            name='imgesAdd',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
