# Generated by Django 3.1.6 on 2021-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0017_formsapp_multiplechoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsapp',
            name='multipleChoices',
        ),
        migrations.CreateModel(
            name='form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleChoices', models.ManyToManyField(to='formss.formsApp')),
            ],
        ),
    ]
